### PR TITLE
( feat ) Implemented client-side route restrictions [Closes #41]

### LINKED ISSUE #41: Authentication using Parse sessions

### PR DESCRIPTION
**Pull request by lsavage92**
We stored the userId and sessionToken on the client using cookies. At each state change the sessionToken is checked to see if the user has already been "authenticated" and if they are not, we redirect them to the signin state. Keep in mind, we are currently only checking for the presence of the session token and not the validity of the token itself.

cookies

### CODE REVIEW

**Comment by wezleytsai** [comment]
Note that `.success` and `.error` are deprecated and that we should be using `.then`. Any reason why you changed it?
https://docs.angularjs.org/api/ng/service/$http

**Comment by kamerynn** [comment]
We thought it was more clear (seeing success and error is more intuitive than two methods in .then) and we had used it elsewhere, but didn't know that it was deprecated!

**Comment by dvc94ch** [comment]
Why did you add a .travis.yml file?

**Comment by kamerynn** [comment]
Not sure why that's in there... @lsavage92 , is that something that was part of older code and didn't get removed in the rebase?

**Pull request merged**
